"""empty message

Revision ID: 51ae747709ff
Revises: 821602078adc
Create Date: 2023-07-16 01:02:43.969265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ae747709ff'
down_revision = '821602078adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Field', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('Group', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Group', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Field', 'year')
    # ### end Alembic commands ###
